### PR TITLE
PLT-7457 Fixed runtime error "UNIQUE constraint failed: lastSync.slotNo"

### LINKED ISSUE #153: marconi-sidechain has sqlite errors when starting from scratch
Hi guys :)

So I was trying to benchmark marconi-sidechain, but it fails with this error: `marconi-sidechain: an indexer raised an error: CantInsertEvent "SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: lastSync.slotNo"`

Full output:
```
[marconi-sidechain:Info:19] [2023-09-11 16:20:44.75 UTC] marconi-sidechain-1.2.0.0-4060e883364ce86e525949eba4c6d75bf212ce80
[marconi-sidechain:Info:19] [2023-09-11 16:20:44.75 UTC] CliArgs
    { socketFilePath = "/home/user/mainnet/socket/node.socket"
    , nodeConfigPath = "/home/user/mainnet/config/config.json"
    , dbDir = "dbs"
    , httpPort = Nothing
    , networkId = Mainnet
    , minIndexingDepth = MinIndexingDepth 0
    , targetAddresses = Nothing
    , targetAssets = Nothing
    , optionsFailsIfResync = False
    , optionsRetryConfig = RetryConfig
        { baseTimeBeforeNextRetry = 30
        , maybeMaxWaitTime = Just 1800
        }
    }
[marconi-sidechain:Info:41] [2023-09-11 16:20:45.22 UTC] Resumable points for each indexer:
    [ChainPointAtGenesis, ChainPointAtGenesis, ChainPointAtGenesis]
[marconi-sidechain:Info:41] [2023-09-11 16:20:45.22 UTC] Starting from ChainPointAtGenesis. 
marconi-sidechain: an indexer raised an error: CantInsertEvent "SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: lastSync.slotNo"
CallStack (from HasCallStack):
  error, called at src/Marconi/ChainIndex/Indexers.hs:766:7 in marconi-chain-index-1.2.0.0-inplace:Marconi.ChainIndex.Indexers
[marconi-sidechain:Info:41] [2023-09-11 16:20:45.69 UTC] Stopping indexing. Waiting for indexers to finish their work (timeout after 180s) ...
marconi-sidechain: an indexer raised an error: CantInsertEvent "SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: lastSync.slotNo"
CallStack (from HasCallStack):
  error, called at src/Marconi/ChainIndex/Indexers.hs:766:7 in marconi-chain-index-1.2.0.0-inplace:Marconi.ChainIndex.Indexers
[marconi-sidechain:Info:41] [2023-09-11 16:20:45.69 UTC] Done!
marconi-sidechain: CantInsertEvent "SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed: lastSync.slotNo"
```

### PR DESCRIPTION
**Pull request by koslambrou**
Fixes #153

We get a runtime error "UNIQUE constraint failed: lastSync.slotNo" when running marconi-chain-index and marconi-sidechain on mainnet.

Replaced the use of SlotNo as a primary key for some tables with the composite primary key (SlotNo, BlockHeaderHash) because we can have two blocks in the same slot in Byron era.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense and have useful messages
    - [ ] Important changes are reflected in changelog.d of the affected packages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting main unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] If relevant, reference the ADR in the PR and reference the PR in the ADR
    - [ ] Reviewer requested

### CODE REVIEW

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs [hunk 1]
```diff
@@ -336,28 +344,35 @@ mkMintTokenIndexer dbPath = do
...
-        [createMintPolicyEvent, createMintPolicyIdIndex, Sync.syncTableCreation]
+        [createMintPolicyEvent, createMintPolicyIdIndex]
       mintInsertPlans = [Core.SQLInsertPlan fromTimedMintEvents mintEventInsertQuery]
+      lastSyncPointQuery :: Core.GetLastSyncPointsQuery
+      lastSyncPointQuery = Core.GetLastSyncPointsQuery $ \limit ->
+        [sql|SELECT slotNo, blockHeaderHash
+             FROM minting_policy_events
+             ORDER BY slotNo DESC, blockNo DESC
+             LIMIT |]
+          <> fromString (show limit)
```
Comment (berewt) [inline marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs:366]: It won't work because we don't have exactly 1 event in each block. We'll either have duplicate blocks or missing ones.
(It's why I added the atrocious sync table, and we'll have to redesign it in another way).

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Spent.hs [hunk 2]
```diff
@@ -103,37 +109,47 @@ mkSpentIndexer path = do
...
                )
-               VALUES (?, ?, ?, ?)|]
+               VALUES (?, ?, ?, ?, ?, ?)|]
+      lastSyncPointQuery :: Core.GetLastSyncPointsQuery
+      lastSyncPointQuery = Core.GetLastSyncPointsQuery $ \limit ->
+        [sql|SELECT slotNo, blockHeaderHash
+             FROM spent
+             ORDER BY slotNo DESC, blockNo DESC
+             LIMIT |]
+          <> fromString (show limit)
```
Comment (berewt) [inline marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Spent.hs:140]: As for the mint indexer, we may be out of sync on block without tx.

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs [hunk 3]
```diff
@@ -140,25 +143,33 @@ mkUtxoIndexer path = do
...
       createUtxoTables =
-        [ Sync.syncTableCreation
-        , createUtxo
+        [ createUtxo
         , createAddressIndex
         , createSlotNoIndex
         ]
       insertEvent = [Core.SQLInsertPlan (traverse NonEmpty.toList) utxoInsertQuery]
+
+      lastPointQuery :: Core.GetLastSyncPointsQuery
```
Comment (berewt) [inline marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Utxo.hs:158]: Still the same issue (even worse if we track a limited set of addresses).

File: marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs [hunk 4]
```diff
@@ -626,9 +626,9 @@ mkIndexerStream' f coordinator =
       waitQSemN _barrier _indexerCount
       pure c'
 
-    -- give 3 minutes (180s) for a step to finish
+    -- give 30 minutes (1800s) for a step to finish
```
Comment (berewt) [inline marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs:629]: Isn't that too much?

**Review by berewt — CHANGES_REQUESTED** [review]
Some sync table deletions may lead to new issues and need to be fixed, but the rest is good.

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Datum.hs [hunk 5]
```diff
@@ -90,34 +96,46 @@ type DatumIndexer = Core.SQLiteIndexer DatumEvent
...
   :: (MonadIO m, MonadError Core.IndexerError m)
   => FilePath
   -> m (Core.SQLiteIndexer DatumEvent)
 mkDatumIndexer path = do
   let createDatumQuery =
-        [sql|CREATE TABLE IF NOT EXISTS datum (datumHash BLOB PRIMARY KEY, datum BLOB, slotNo Int)|]
+        [sql|CREATE TABLE IF NOT EXISTS datum
+             ( datumHash BLOB PRIMARY KEY
+             , datum BLOB
+             , blockNo INT
```
[the remark this answers is not in the document]
Comment (koslambrou) [reply marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Datum.hs:109]: For the same reason as the other indexers. We need to order by slotNo and blockNo when querying for the last sync point.

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Datum.hs
[the remark this answers is not in the document]
Comment (koslambrou) [reply marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Datum.hs:1]: Missed it! Thanks :)

File: marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs (hunk 4 above)
Comment (koslambrou) [reply marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs:629]: 3 minutes wasn't enough on mainnet. Made it fail. Still failed at 5min, so I thought to just put a large enough number. Then again, something between 15min or 30min, not much difference. I don't mind 15min though.

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Datum.hs (hunk 5 above)
[the remark this answers is not in the document]
Comment (berewt) [reply marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/Datum.hs:109]: For lastSyncPoints, we have to use the sync table though, as discussed today (and we agree that its both sad and bad).

File: marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs (hunk 4 above)
Comment (berewt) [reply marconi-chain-index/src/Marconi/ChainIndex/Indexers.hs:629]: I wouldn't thought it would take that long. We should definitely push it to a separate thread. We can keep it to 30 minutes atm and we'll work on it in another ticket.

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs [hunk 6]
```diff
@@ -94,19 +94,23 @@ mkBlockInfoIndexer
 mkBlockInfoIndexer path = do
   let createBlockInfo =
         [sql|CREATE TABLE IF NOT EXISTS blockInfo
-               ( slotNo INT PRIMARY KEY
+               ( slotNo INT NOT NULL
                , blockHeaderHash BLOB NOT NULL
```
[the remark this answers is not in the document]
Comment (koslambrou) [reply marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/BlockInfo.hs:98]: Shouldn't hurt, and makes more explicit.

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs [hunk 7]
```diff
@@ -520,43 +528,44 @@ instance
...
-                      Just BurnEventType -> Just "quantity < 0"
-                  whereClause =
-                    fmap (\e -> Text.intercalate " AND " $ NonEmpty.toList e) $
-                      NonEmpty.nonEmpty $
-                        catMaybes [policyIdWhereClause, assetNameWhereClause, eventTypeWhereClause]
-               in mintTokenEventQueryByAssetId whereClause
-          )
-          (const toTimedMintEvents)
+    Core.querySyncedOnlySQLiteIndexerWith
+      ( \cp ->
```
Comment (berewt) [inline marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs:532]: create a local function?

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs [hunk 8]
```diff
@@ -520,43 +528,44 @@ instance
...
+              [ ":slotNo" := C.chainPointToSlotNo cp
+              , ":policyId" := policyId
+              , ":assetName" := assetName
+              ]
+            QueryByAssetId policyId Nothing _ ->
+              [ ":slotNo" := C.chainPointToSlotNo cp
+              , ":policyId" := policyId
+              ]
+      )
+      ( \(QueryByAssetId _ assetNameM eventType) ->
```
Comment (berewt) [inline marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs:544]: create a local function as well?

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs [hunk 9]
```diff
@@ -520,43 +528,44 @@ instance
...
+  SQL.Query $
+    Text.intercalate " " $
+      catMaybes
+        [ Just
+            "SELECT slotNo, blockHeaderHash, blockNo, txId, txIndexInBlock, policyId, assetName, quantity, redeemerHash, redeemerData"
+        , Just "FROM minting_policy_events"
+        , Just "WHERE slotNo <= :slotNo"
+        , fmap (\e -> Text.append " AND " e) whereClauseM
+        , Just "ORDER BY slotNo ASC, blockNo ASC, txIndexInBlock ASC"
+        ]
```
Comment (berewt) [inline marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs:571]:
```
[sql|
  SELECT
    slotNo,
    blockHeaderHash,
    blockNo,
    txId,
    txIndexInBlock,
    policyId,
    assetName,
    quantity,
    redeemerHash,
    redeemerData
  FROM minting_policy_events
  WHERE slotNo <= :slotNo
]
<> maybe "" (" AND " <> e) whereClauseM
<> [sql|ORDER BY slotNo ASC, blockNo ASC, txIndexInBlock ASC]
```

**Review by berewt — APPROVED** [review]
Cosmetic changes mostly

File: marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs (hunk 9 above)
Comment (koslambrou) [reply marconi-chain-index/src/Marconi/ChainIndex/Experimental/Indexers/MintTokenEvent.hs:571]: My issue with this approach is the addition of spaces which are hard to spot if an error occurs.
For example, the ORDER BY statement needs a space:

```
[sql| ORDER BY slotNo ASC, blockNo ASC, txIndexInBlock ASC]
```
